### ISSUE TITLE
KeyKey crashes on macOS 14.2, hindering users from exporting user phrases.

### ISSUE THREAD

**Issue by ShikiSuen** [Yi-Kai/homebrew-yahoo-keykey#6]
雅虎奇摩輸入法 macOS 版的輸入法本體對 __objc_empty_cache 有強制依賴。然而，Apple 自 macOS 14.2 Beta 1 開始移除了這個 API、導致了兩個問題：

1. 奇摩輸入法本體徹底罷工。
2. 因為奇摩輸入法本體徹底罷工，導致無法藉由 XPC 通訊手段從輸入法本體匯出使用者自訂詞庫。（奇摩輸入法的偏好設定是一個獨立的 App、與輸入法本體之間採 XPC 通訊。）

很多人使用雅虎奇摩輸入法十幾年了，各自的使用者語彙資料積累無法輕易捨棄。然而，奇摩輸入法的使用者辭典是經過 CEROD 加密的。這個加密模組早在 2012 年底就變成了收費套件，是奇摩輸入法專案結案的主要原因。

使用者自訂詞庫資料不該被這種加密所套牢。希望奇摩輸入法能有專門的使用者辭典匯出工具，畢竟不是誰都懂得將相關的 SQLite db 加密檔案拷貝到 Windows 系統下藉由 Windows 版奇摩注音來匯出。

![image](https://github.com/Yi-Kai/homebrew-yahoo-keykey/assets/3164826/6166c7bc-70e8-49aa-a99e-cf55e55e3f2a)

**Comment by Yi-Kai** [comment]
Thank @ShikiSuen's value feedback. 
I had upgraded to 14.2.1 , for now it is working.

**Comment by ShikiSuen** [comment]
@Yi-Kai Thanks for your response.

Note that the Rosetta 2 is scheduled for its complete removal since macOS 27. This eliminates Yahoo KeyKey since then.

This year is the final year for all Yahoo KeyKey users to dump their user phrases out. I wrote a CLI utility for this purpose: https://github.com/ShikiSuen/KimoUserDataDumper
